[project]
name = "weicityback"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "eztable>=0.1.3",
    "natsort>=8.4.0",
    "numpy>=2.2.4",
    "openai>=1.72.0",
    "opencv-python>=4.11.0.86",
    "polars>=1.27.0",
    "requests>=2.32.3",
    "snoop>=0.6.0",
    "trio>=0.30.0",
]
